export default {
  port: "PORT",
  dbName: "MONGODB_USERNAME",
  dbPass: "MONGODB_PASSWORD",
  accessTokenExpiresIn: "ACCESS_TOKEN_EXPIRATION",
  refreshTokenExpiresIn: "REFRESH_TOKEN_EXPIRATION",
  accessTokenPrivateKey: "ACCESS_TOKEN_PRIVATE_KEY",
  accessTokenPublicKey: "ACCESS_TOKEN_PUBLIC_KEY",
  refreshTokenPrivateKey: "REFRESH_TOKEN_PRIVATE_KEY",
  refreshTokenPublicKey: "REFRESH_TOKEN_PUBLIC_KEY",
  googleClientId: "GOOGLE_OAUTH_CLIENT_ID",
  googleClientSecret: "GOOGLE_OAUTH_CLIENT_SECRET",
  googleOauthRedirect: "GOOGLE_OAUTH_REDIRECT_URL",
  rapidApiKey: "RAPIDAPI_KEY",
  rapidApiHost: "RAPIDAPI_HOST",
  initializationPlaylistIds: "INITIALIZATION_PLAYLIST_IDS",
};
